### ISSUE TITLE
get_episodes_by_series() does not exist anymore

### ISSUE THREAD

**Issue by DylanVanAssche** [spapanik/tvdb_api_client#2]
# Description

The latest release lacks the method `get_episodes_by_series` in `TVDBClient`.
There's a mistake in the indentation of the class.

# Steps to reproduce
1. Upgrade to the latest release with `pip`
2. Try to call `get_episodes_by_series` on an instance of the `TVDBClient` class
3. An `ImportError` is raised: `ImportError: cannot import name 'get_episodes_by_series' from 'tvdb_api_client' `

**Comment by spapanik** [comment]
Added in v0.4.1
