### ISSUE TITLE
user_key

### ISSUE THREAD

**Issue by daomengRen** [spapanik/tvdb_api_client#5]
Hello, where can I get the user_key, and can the project continue to be used now, thank you

**Comment by spapanik** [comment]
This field was for the v3 of the TVDB API, I'm currently in the process of re-writting it for V4.

**Comment by daomengRen** [comment]
Ok, looking forward to your update, thank you

**Comment by spapanik** [comment]
The V4 re-write is underway, you can use your API key, that you can get from [here](https://thetvdb.com/dashboard/account/apikey).

**Comment by daomengRen** [comment]
how can I install this module, can pip install it

**Comment by spapanik** [comment]
yes,  you can `pip install tvdb-api-client`

**Comment by daomengRen** [comment]
Last question, does user_key refer to my password
